name: D

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  dub_test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Setup D compiler
      uses: dlang-community/setup-dlang@v1.3.0
      with:
        compiler: ldc-1.32.0

    - name: Install deps
      run: |
        sudo apt-get install libgit2-dev

    - name: Build
      run: |
        dub build --config=single-commit-clone
